name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test -- --coverage
      
      - name: Deploy
        run: npm run build

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
    
  release:
    name: deploy
    runs-on: ubuntu-latest
    needs: deploy
    environment: Developer
    steps:
      - name: Dowload artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy dist/practice4/index.js --name bold-band-9c54 --compatibility-date 2026-02-26 --compatibility-flags nodejs_compat --assets  dist/client
          
        